"""
Django settings for 32GSMgatewayServer project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-^d20n=e3mb!7%e4d26@8!&*e5bl4xzb-(!^3s*d#)=f6%sy&&9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# Allow all host headers
ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'status'

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'gsm_gateway.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'gsm_gateway.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



#API CREDENTIALS
API_CREDENTIALS = {
    'SYSTEM_PASSWORD': 'systemPass123',
    'HOST': 'host2',
}


BASE_URL = "https://asterisk.sabkiapp.com"
GATEWAY_IP = "192.168.8.60"
MACHINE_URL = f"http://{GATEWAY_IP}"


MACHINE_USERNAME    = "admin"
MACHINE_PASSWORD    = "AdminAdmin1"
MACHINE_COOKIE_FILE = os.path.join(BASE_DIR, "voip_gateway_cookies.pkl")




PORT = 9000
VPS_PRT = 9001
HTML_PRT = 3000
DOWNLOADER_PRT = 8000
SUDO_PASS = "123"

STATICFILES_DIRS = [
    "/home/pi/Documents",
]


UPDATED_TIME = "2024-04-10 15:07:14"


COPY_TIME = "2024-04-10 15:01:15"



# ── Central server Ed25519 public key (for JWT verification) ──
_DEV_ED25519_PUB = Path(BASE_DIR, "dev_keys", "host_ed25519_public.pem")
if _DEV_ED25519_PUB.exists():
    CENTRAL_ED25519_PUBLIC_KEY = _DEV_ED25519_PUB.read_text()
else:
    CENTRAL_ED25519_PUBLIC_KEY = os.environ.get("CENTRAL_ED25519_PUBLIC_KEY", "")
