# Generated by Django 4.2.6 on 2024-02-08 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dialplan',
            old_name='sms_id',
            new_name='template',
        ),
        migrations.AddField(
            model_name='dialplan',
            name='name_gender',
            field=models.IntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Others')], default=1),
            preserve_default=False,
        ),
    ]
