# Generated by Django 4.2.6 on 2024-02-13 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_namepronunciation_status_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='smscampaign',
            unique_together={('user', 'name')},
        ),
    ]
