# Generated by Django 4.2.6 on 2024-02-08 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_callstatus_created_at_remove_dialplan_sms_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='calldtmfstatus',
            unique_together={('call_id', 'extension')},
        ),
    ]
