# Generated by Django 4.2.6 on 2024-02-08 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_campaign_language_campaign_name_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dialplan',
            name='name_gender',
        ),
    ]
