# Generated by Django 4.2.6 on 2024-03-07 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_contacts_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='misscallmanagement',
            name='campaign_associated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.campaign'),
        ),
    ]
