# Generated by Django 4.2.6 on 2024-02-28 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_smsdialer_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsdialer',
            name='sms_through',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
    ]
