# Generated by Django 4.2.6 on 2024-03-11 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_users_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='user_id',
        ),
    ]
