# Generated by Django 4.2.11 on 2024-03-13 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_users_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonedialer',
            name='duration',
            field=models.IntegerField(blank=True, db_index=True, default=0, null=True),
        ),
    ]
