# Generated by Django 4.2.6 on 2024-02-21 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        # ('api', '0010_delete_campaigncontacts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phonedialer',
            old_name='user_id',
            new_name='user',
        ),
    ]
