# Generated by Django 4.2.6 on 2024-02-12 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_smscampaign_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smscampaign',
            name='status',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
