# Generated by Django 4.2.6 on 2024-02-21 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_campaign_allow_repeat_phonedialer_trials'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveCampaignHosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(db_index=True, default=0)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.campaign')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userhosts')),
            ],
            options={
                'verbose_name': 'Active Campaign Host',
                'verbose_name_plural': 'Active Campaign Hosts',
            },
        ),
    ]
