# Generated by Django 4.2.6 on 2024-02-28 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_smstemplate_template_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsdialer',
            name='sms_sent',
            field=models.TextField(null=True),
        ),
    ]
