# Generated by Django 4.2.6 on 2024-02-23 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_callstatus_dial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callstatus',
            name='dial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.phonedialer', unique=True),
        ),
    ]
