# Generated by Django 4.2.11 on 2024-04-02 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_phonedialer_block_trials'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_number', models.BigIntegerField()),
                ('campaign_id', models.IntegerField()),
                ('host', models.CharField(max_length=255)),
                ('port', models.IntegerField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
