# Generated by Django 4.2.11 on 2024-04-16 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_callinfo_status_alter_callinfo_campaign_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='misscallmanagement',
            name='update_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
