# Generated by Django 4.2.6 on 2024-02-27 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_rename_misscall_management_id_misscalls_misscall_management'),
    ]

    operations = [
        migrations.RenameField(
            model_name='misscallmanagement',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='misscallmanagement',
            name='send_sms_status',
        ),
        migrations.RemoveField(
            model_name='misscallmanagement',
            name='sms_template',
        ),
    ]
