# Generated by Django 4.2.6 on 2024-02-27 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_alter_misscallmanagement_associated_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='misscallmanagement',
            name='status',
            field=models.IntegerField(db_index=True, default=1),
        ),
    ]
