# Generated by Django 4.2.6 on 2024-02-27 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_alter_misscalls_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='misscallmanagement',
            name='management_id',
            field=models.CharField(db_index=True, default=1, max_length=10),
            preserve_default=False,
        ),
    ]
