# Generated by Django 4.2.6 on 2024-02-27 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_alter_misscallmanagement_management_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='misscalls',
            name='number_code',
            field=models.CharField(db_index=True, default=1, max_length=10),
            preserve_default=False,
        ),
    ]
