# Generated by Django 5.0.1 on 2025-06-25 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_campaign_no_key_voice_campaign_wrong_key_voice_and_more'),
        ('api', '0005_rename_main_voice_id_dialplan_main_voice_and_more'),
        ('api', '0006_alter_calldtmfstatus_unique_together'),
        ('api', '0009_campaign_language_campaign_no_key_voice_and_more'),
        ('api', '0012_campaign_contacts_count'),
        ('api', '0016_dialplan_name_spell'),
        ('api', '0018_smsdialer_sms_sent'),
        ('api', '0028_alter_siminformation_today_block_status'),
        ('api', '0053_remove_smscampaign_template_id_smscampaign_template'),
    ]

    operations = [
    ]
