# Generated by Django 5.0.1 on 2025-06-25 10:34

import api.models.contacts
import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallDtmfStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension', models.IntegerField(db_index=True, default=0)),
                ('dtmf_response', models.IntegerField(db_index=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CallInfo',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('phone_number', models.BigIntegerField(blank=True, db_index=True, default=0, null=True)),
                ('campaign_id', models.IntegerField(blank=True, db_index=True, default=0, null=True)),
                ('host', models.CharField(blank=True, db_index=True, default='', max_length=255, null=True)),
                ('port', models.IntegerField(blank=True, db_index=True, default=0, null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('status', models.IntegerField(blank=True, db_index=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('phone_number', models.CharField(db_index=True, max_length=10, validators=[api.models.contacts.phone_number_validator])),
                ('user_id', models.IntegerField(db_index=True)),
                ('category_1', models.CharField(blank=True, db_index=True, default='Others', max_length=50)),
                ('category_2', models.CharField(blank=True, db_index=True, default='Others', max_length=50)),
                ('category_3', models.CharField(blank=True, db_index=True, default='Others', max_length=50)),
                ('category_4', models.CharField(blank=True, db_index=True, default='Others', max_length=50)),
                ('category_5', models.CharField(blank=True, db_index=True, default='Others', max_length=50)),
                ('status', models.IntegerField(db_index=True, default=1, null=True)),
            ],
            options={
                'db_table': 'api_contacts',
            },
        ),
        migrations.CreateModel(
            name='DialPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('dtmf_0', models.IntegerField(blank=True, db_index=True, null=True)),
                ('dtmf_1', models.IntegerField(blank=True, db_index=True, null=True)),
                ('dtmf_2', models.IntegerField(blank=True, db_index=True, null=True)),
                ('dtmf_3', models.IntegerField(blank=True, db_index=True, null=True)),
                ('dtmf_4', models.IntegerField(blank=True, db_index=True, null=True)),
                ('dtmf_5', models.IntegerField(blank=True, db_index=True, null=True)),
                ('dtmf_6', models.IntegerField(blank=True, db_index=True, null=True)),
                ('dtmf_7', models.IntegerField(blank=True, db_index=True, null=True)),
                ('dtmf_8', models.IntegerField(blank=True, db_index=True, null=True)),
                ('dtmf_9', models.IntegerField(blank=True, db_index=True, null=True)),
                ('sms_after', models.IntegerField(blank=True, db_index=True, null=True, validators=[django.core.validators.MinValueValidator(-2), django.core.validators.MaxValueValidator(9)])),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('name_spell', models.IntegerField(blank=True, db_index=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)])),
                ('continue_to', models.IntegerField(blank=True, db_index=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MisscallManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('operator', models.CharField(db_index=True, max_length=11)),
                ('associated_number', models.CharField(blank=True, db_index=True, max_length=15, null=True)),
                ('status', models.IntegerField(db_index=True, default=1)),
                ('management_id', models.CharField(max_length=10, unique=True)),
                ('update_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'api_misscall_management',
            },
        ),
        migrations.CreateModel(
            name='Misscalls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=10)),
                ('datetime', models.DateTimeField(db_index=True)),
            ],
            options={
                'db_table': 'api_misscalls',
            },
        ),
        migrations.CreateModel(
            name='NamePronunciation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneDialer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=10)),
                ('sent_status', models.IntegerField(blank=True, db_index=True, default=0, null=True)),
                ('name', models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True)),
                ('sent_datetime', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('trials', models.IntegerField(blank=True, db_index=True, default=0, null=True)),
                ('call_through', models.CharField(blank=True, db_index=True, default=None, max_length=10, null=True)),
                ('duration', models.IntegerField(blank=True, db_index=True, default=0, null=True)),
                ('created_at', models.DateTimeField(db_index=True)),
                ('updated_at', models.DateTimeField(db_index=True)),
                ('block_trials', models.IntegerField(blank=True, db_index=True, default=0, null=True)),
            ],
            options={
                'db_table': 'api_phone_dialer',
            },
        ),
        migrations.CreateModel(
            name='SimInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(db_index=True, max_length=100)),
                ('sim_imsi', models.CharField(db_index=True, max_length=100)),
                ('phone_no', models.CharField(blank=True, db_index=True, max_length=15, null=True)),
                ('sms_backup_date', models.DateField(blank=True, db_index=True, default='2024-02-17', null=True)),
                ('sms_balance', models.IntegerField(blank=True, db_index=True, default=100, null=True)),
                ('validity', models.DateField(blank=True, db_index=True, null=True)),
                ('last_validity_check', models.DateTimeField(blank=True, db_index=True, default='2024-02-17 11:34:14', null=True)),
                ('calls_made_total', models.IntegerField(blank=True, db_index=True, default=0, null=True)),
                ('calls_made_today', models.IntegerField(blank=True, db_index=True, default=0, null=True)),
                ('call_time_total', models.IntegerField(blank=True, db_index=True, default=0, null=True)),
                ('call_time_today', models.IntegerField(blank=True, db_index=True, default=0, null=True)),
                ('call_status_date', models.DateField(blank=True, db_index=True, default='2024-02-17', null=True)),
                ('last_call_time', models.DateTimeField(blank=True, db_index=True, default='2024-02-17 11:34:14', null=True)),
                ('today_block_status', models.DecimalField(blank=True, db_index=True, decimal_places=2, default=0.0, max_digits=5, null=True)),
                ('call_after', models.IntegerField(blank=True, db_index=True, default=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SmsCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField()),
                ('priority', models.IntegerField(db_index=True)),
                ('start_time', models.TimeField(db_index=True)),
                ('end_time', models.TimeField(db_index=True)),
                ('status', models.IntegerField(blank=True, db_index=True, default=1, null=True)),
                ('contact_count', models.IntegerField(blank=True, db_index=True, default=0, null=True)),
                ('start_date', models.DateField(db_index=True, default=datetime.date(2024, 1, 1))),
                ('end_date', models.DateField(db_index=True, default=datetime.date(2050, 12, 31))),
            ],
        ),
        migrations.CreateModel(
            name='SmsDialer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=15)),
                ('sent_status', models.IntegerField(blank=True, db_index=True, default=0, null=True)),
                ('sent_datetime', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('sms_through', models.CharField(blank=True, db_index=True, max_length=10, null=True)),
                ('sms_sent', models.TextField(blank=True, null=True)),
                ('sms_count', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'db_table': 'api_sms_dialer',
            },
        ),
        migrations.CreateModel(
            name='SmsTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(db_index=True, max_length=766)),
                ('template', models.TextField()),
                ('status', models.IntegerField(db_index=True, default=1)),
            ],
        ),
        migrations.CreateModel(
            name='UserHosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(db_index=True, max_length=255)),
                ('system_password', models.CharField(db_index=True, max_length=255)),
                ('priority', models.IntegerField(db_index=True, default=0)),
                ('status', models.IntegerField(db_index=True, default=1)),
                ('allow_sms', models.IntegerField(db_index=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Voices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice_name', models.CharField(db_index=True, max_length=255, verbose_name='voice_name')),
                ('voice_desc', models.TextField(blank=True, null=True, verbose_name='voice_desc')),
                ('path', models.CharField(db_index=True, max_length=500)),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('status', models.IntegerField(db_index=True, default=1)),
            ],
            options={
                'verbose_name': 'Voice',
                'verbose_name_plural': 'Voices',
                'db_table': 'api_audios',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('mobile_number', models.CharField(db_index=True, max_length=15, unique=True)),
                ('password', models.CharField(db_index=True, max_length=255)),
                ('status', models.IntegerField(db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('api_key', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('ref_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_users', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('name_spell', models.IntegerField(blank=True, db_index=True, default=0, null=True)),
                ('description', models.TextField(null=True)),
                ('call_cut_time', models.IntegerField(db_index=True)),
                ('start_time', models.TimeField(db_index=True)),
                ('end_time', models.TimeField(db_index=True)),
                ('start_date', models.DateField(db_index=True, default=datetime.date(2024, 1, 1))),
                ('end_date', models.DateField(db_index=True, default=datetime.date(2050, 12, 31))),
                ('campaign_priority', models.IntegerField(db_index=True, default=1)),
                ('status', models.IntegerField(db_index=True, default=0)),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('contacts_count', models.IntegerField(db_index=True, default=0)),
                ('language', models.CharField(choices=[('hi', 'Hindi'), ('en', 'English'), ('pa', 'Punjabi'), ('mr', 'Marathi'), ('gu', 'Gujarati'), ('bn', 'Bengali'), ('ta', 'Tamil'), ('te', 'Telugu'), ('ml', 'Malayalam'), ('ka', 'Kannada'), ('as', 'Assamese'), ('or', 'Oriya')], db_index=True, default='hi', max_length=2)),
                ('allow_repeat', models.IntegerField(db_index=True, default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CallStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$')])),
                ('port', models.IntegerField(db_index=True)),
                ('start_time', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('duration', models.IntegerField(db_index=True, default=0)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='ActiveCampaignHosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(db_index=True, default=0)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.campaign')),
            ],
            options={
                'verbose_name': 'Active Campaign Host',
                'verbose_name_plural': 'Active Campaign Hosts',
            },
        ),
        migrations.AddConstraint(
            model_name='contacts',
            constraint=models.UniqueConstraint(fields=('phone_number', 'user_id'), name='unique_phone_per_user'),
        ),
        migrations.AddField(
            model_name='dialplan',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.campaign'),
        ),
        migrations.AddField(
            model_name='misscallmanagement',
            name='campaign_associated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.campaign'),
        ),
        migrations.AddField(
            model_name='misscallmanagement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='misscalls',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.campaign'),
        ),
        migrations.AddField(
            model_name='misscalls',
            name='misscall_management',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.misscallmanagement'),
        ),
        migrations.AddField(
            model_name='namepronunciation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='phonedialer',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.campaign'),
        ),
        migrations.AddField(
            model_name='phonedialer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='callstatus',
            name='dial',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.phonedialer'),
        ),
        migrations.AddField(
            model_name='calldtmfstatus',
            name='call_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.phonedialer'),
        ),
        migrations.AddConstraint(
            model_name='siminformation',
            constraint=models.UniqueConstraint(fields=('host', 'sim_imsi'), name='unique_host_sim_imsi'),
        ),
        migrations.AddField(
            model_name='smscampaign',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='smsdialer',
            name='sms_campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.smscampaign'),
        ),
        migrations.AddField(
            model_name='smsdialer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='smstemplate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='smsdialer',
            name='sms_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.smstemplate'),
        ),
        migrations.AddField(
            model_name='smscampaign',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.smstemplate'),
        ),
        migrations.AddField(
            model_name='dialplan',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_id', to='api.smstemplate'),
        ),
        migrations.AddField(
            model_name='userhosts',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='callstatus',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userhosts'),
        ),
        migrations.AddField(
            model_name='activecampaignhosts',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userhosts'),
        ),
        migrations.AddField(
            model_name='voices',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dialplan',
            name='main_voice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_voice', to='api.voices'),
        ),
        migrations.AddField(
            model_name='dialplan',
            name='option_voice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='option_voice_id', to='api.voices'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='no_key_voice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='no_key_voice', to='api.voices'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='wrong_key_voice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wrong_key_voice', to='api.voices'),
        ),
        migrations.AlterUniqueTogether(
            name='calldtmfstatus',
            unique_together={('call_id', 'extension')},
        ),
        migrations.AlterUniqueTogether(
            name='smstemplate',
            unique_together={('user', 'template_name')},
        ),
        migrations.AlterUniqueTogether(
            name='smscampaign',
            unique_together={('user', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='userhosts',
            unique_together={('host', 'priority')},
        ),
        migrations.AlterUniqueTogether(
            name='voices',
            unique_together={('user', 'voice_name')},
        ),
        migrations.AlterUniqueTogether(
            name='dialplan',
            unique_together={('campaign', 'extension_id')},
        ),
        migrations.AlterUniqueTogether(
            name='campaign',
            unique_together={('name', 'user')},
        ),
    ]
