# Generated by Django 5.0.1 on 2025-06-25 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonedialer',
            name='channel_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='phonedialer',
            name='ref_no',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='phonedialer',
            name='surveyer_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
