# Generated by Django 5.0.1 on 2025-06-25 11:06

import api.models.phone_dialer
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_phonedialer_channel_name_phonedialer_ref_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonedialer',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=api.models.phone_dialer.now_ist),
        ),
        migrations.AlterField(
            model_name='phonedialer',
            name='updated_at',
            field=models.DateTimeField(db_index=True, default=api.models.phone_dialer.now_ist),
        ),
    ]
