# Generated by Django 5.0.1 on 2025-06-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_errorverifyphonedialer'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorverifyphonedialer',
            name='verify_datetime',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='errorverifyphonedialer',
            index=models.Index(fields=['verify_datetime'], name='api_error_v_verify__6e850d_idx'),
        ),
    ]
