# Generated by Django 5.0.1 on 2025-06-25 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_errorverifyphonedialer_verify_datetime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phonedialer',
            old_name='surveyer_name',
            new_name='surveyor_name',
        ),
    ]
