# Generated by Django 5.0.1 on 2025-06-26 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_surveyer_name_phonedialer_surveyor_name'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='errorverifyphonedialer',
            name='api_error_v_verify__6e850d_idx',
        ),
        migrations.RemoveField(
            model_name='errorverifyphonedialer',
            name='verify_datetime',
        ),
    ]
