# Generated by Django 5.0.1 on 2025-06-27 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_errorverifyphonedialer_api_error_v_verify__6e850d_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorverifyphonedialer',
            name='ref_no',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='phonedialer',
            name='ref_no',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
