# Generated by Django 5.0.1 on 2025-07-05 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_errorverifyphonedialer_ref_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonedialer',
            name='gender',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
    ]
