# Generated by Django 5.0.1 on 2025-07-08 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_phonedialer_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransliterationCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_text', models.TextField()),
                ('text_hash', models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True)),
                ('transliterated_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'transliteration_cache',
            },
        ),
    ]
