# Generated by Django 5.0.1 on 2025-07-09 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_transliterationcache'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transliterationcache',
            name='text_hash',
        ),
    ]
