"""
Django settings for DigiCampServer project.

Generated by 'django-admin startproject' using Django 4.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/


SECRET_KEY = "ureq!b3k^jw6p@5b*%0gb@xbm1b8v232(*7wnv*&e)q#49y3re"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

AUTH_USER_MODEL = 'api.Users'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'djoser',
    'api',
    'channels',
    'corsheaders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
]

ROOT_URLCONF = 'digicamp_server.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'Basic': {
            'type': 'basic'
        }
    }
}

WSGI_APPLICATION = 'digicamp_server.wsgi.application'

# ------------------------------------------------------------------
# Caching – Redis backend (shared across all processes)
# ------------------------------------------------------------------
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": os.getenv("REDIS_URL", "redis://127.0.0.1:6379/1"),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
        "TIMEOUT": None,  # respect per-key TTLs
    }
}



# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'sabkiapp_asterisk',                    # Database name
        'USER': 'sabkiapp_asterisk',                        # MySQL username
        'PASSWORD': '@O5[mxJD_k3bsAAk',                # MySQL password
        'HOST': '206.189.130.26',                     # Address of your MySQL instance
        'PORT': '3306',                          # Default MySQL port
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = False


# ────────────────────────────────────────────────────────────────
#  SabkiApp ⇢ DigiCampServer  (incoming JWT validation)
# ────────────────────────────────────────────────────────────────
# SabkiApp RS-256 public key (development: load from dev_public.pem if present)
from pathlib import Path


_DEV_PUB = Path(BASE_DIR, "dev_keys", "sabkiapp_public.pem")
SABKIAPP_PUBLIC_KEY = _DEV_PUB.read_text()

_DEV_VOIP_PRIVATE_KEY = Path(BASE_DIR, "dev_keys", "sabkiapp_voip_private.pem")
SABKIAPP_VOIP_PRIVATE_KEY = _DEV_VOIP_PRIVATE_KEY.read_text()

# ────────────────────────────────────────────────────────────────
#  DigiCamp ⇢ Gateway  (Ed25519 host JWT signing key)
# ────────────────────────────────────────────────────────────────
_DEV_HOST_ED25519_PRIVATE = Path(BASE_DIR, "dev_keys", "host_ed25519_private.pem")
if _DEV_HOST_ED25519_PRIVATE.exists():
    HOST_ED25519_PRIVATE_KEY = _DEV_HOST_ED25519_PRIVATE.read_text()
else:
    import os as _os
    HOST_ED25519_PRIVATE_KEY = _os.environ.get("HOST_ED25519_PRIVATE_KEY", "")

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': (
        # 'rest_framework.permissions.IsAuthenticated',
        # 'rest_framework.permissions.AllowAny'
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=14400),
    'ROTATE_REFRESH_TOKENS': False,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUTH_HEADER_TYPES': ('Bearer',),
}


APPEND_SLASH=False

# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': False,
#     'formatters': {
#         'verbose': {
#             'format': '{levelname} {asctime} {module} {message}',
#             'style': '{',
#         },
#         'simple': {
#             'format': '{levelname} {message}',
#             'style': '{',
#         },
#     },
#     'handlers': {
#         'console': {
#             'class': 'logging.StreamHandler',
#             'formatter': 'verbose',
#         },
#     },
#     'root': {
#         'handlers': ['console'],
#         'level': 'DEBUG',
#     },
# }

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, '')


# ngrok
ALLOWED_HOSTS = ['127.0.0.1', 'localhost', 'call.sabkiapp.com']

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}

ASGI_APPLICATION = 'digicamp_server.asgi.application'

CORS_ALLOWED_ORIGINS = [
    "https://call.sabkiapp.com",
]
CORS_ALLOW_ALL_ORIGINS = True
ALLOWED_HOSTS=['*']

CORS_ORIGIN_ALLOW_ALL = True

CORS_ALLOW_CREDENTIALS = True
CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = True


CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
    'ngrok-skip-browser-warning',
]
# CORS_ALLOW_HEADERS = [
#     "accept",
#     "accept-encoding",
#     "authorization",
#     "content-type",
#     "dnt",
#     "origin",
#     "user-agent",
#     "x-csrftoken",
#     "x-requested-with",
#     "access-control-allow-origin",
#     "access-control-allow-credentials",
# ]
CORS_ALLOW_HEADERS = "*"

CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://call\.sabkiapp\.com$",
]
CORS_ORIGIN_WHITELIST = [
    'https://call.sabkiapp.com',
    # Add other domains if needed
]

import django
from django.utils.encoding import smart_str
django.utils.encoding.smart_text = smart_str


API_KEY_CRONJOB = "dklasjeiopduqw4iohjh480ehhcdjh3u8092"
API_KEY_RETURN_MISS_CALL = "3d2f4b8f9a1c7e6d"
PHONE_ENCRYPTER_KEY = "DDIjoS0ckWyXJHexm6OYdK8XZy8p9YDo"
sabkiapp_password = "3789yduiahy3"
sabkiapp_base_url = "https://bankjaal.com/v2"
sabkiapp_misscall_password = "kranti2024"

# Base URL for SabkiApp API endpoints
SABKIAPP_BASE_URL = "https://staging.sabkiapp.com"

# Celery beat: retry /verify-family queue every 30 min
from celery.schedules import crontab  # noqa: E402  (import after settings)

CELERY_BEAT_SCHEDULE = {
    **globals().get("CELERY_BEAT_SCHEDULE", {}),
    "process-verify-queue-every-30min": {
        "task": "api.process_verify_queue",
        "schedule": crontab(minute="*/30"),
    },
}

# ElevenLabs
ELEVENLABS_API_KEY = "sk_dacd46d3e10e3b268fb37fe1f391eefe6612f48b6cc5cfcf"
ELEVENLABS_VOICE_ID = "RABOvaPec1ymXz02oDQi"          # default – override per-request if you like
ELEVENLABS_MODEL_ID = "eleven_multilingual_v2"



GEMINI_API_KEY="AIzaSyBilUXggzl_ib-3TvwplFhHdwDpVkl2rtU"

# ---------------------------------------------------------------------------
#  Simple host-&-password pairs for the /generate_verification_clip endpoint
#  (hostname → plaintext password).  Edit to suit.
# ---------------------------------------------------------------------------
DIGICAMP_CREDENTIALS = {
    "host1": "secret123",
    "host2": "systemPass123",
}

# -----------------------------  TTS LANG PROFILES  -------------------------- #
# Key  : ISO-639-1 code or custom
# Value: {
#   "voice_id": default ElevenLabs voice,
#   "ctx": {
#       "name": (prev, next),
#       "channel": (prev, next),
#       "surveyor": (prev, next)
#   }
# }
# --------------------------------------------------------------------------- #
VOICE_TTS_LANGS = {
    "hi": {
        "voice_id": "RABOvaPec1ymXz02oDQi",
        "ctx": {
            "name": ("नमस्कार, ", ",जी,।"),
            "channel": ("यह कॉल आपको सबकी ऐप Platform के ", ",चैनल की ओर से"),
            "surveyor": ("चैनल की ओर से ", " द्वारा किया गया है।"),
        },
    },
    "en": {
        "voice_id": "RABOvaPec1ymXz02oDQi",
        "ctx": {
            "name": ("Hello ", ","),
            "channel": ("This call is from the ", " channel, "),
            "surveyor": ("on behalf of ", "."),
        },
    },
    "or": {
        "voice_id": "RABOvaPec1ymXz02oDQi",
        "ctx": {
            "name": ("Hello ", ","),
            "channel": ("This call is from the ", " channel, "),
            "surveyor": ("on behalf of ", "."),
        },
    },
    "mr": {
        "voice_id": "RABOvaPec1ymXz02oDQi",
        "ctx": {
            "name": ("Hello ", ","),
            "channel": ("This call is from the ", " channel, "),
            "surveyor": ("on behalf of ", "."),
        },
    },
    "pa": {
        "voice_id": "RABOvaPec1ymXz02oDQi",
        "ctx": {
            "name": ("Hello ", ","),
            "channel": ("This call is from the ", " channel, "),
            "surveyor": ("on behalf of ", "."),
        },
    },
    "tel": {
        "voice_id": "RABOvaPec1ymXz02oDQi",
        "ctx": {
            "name": ("Hello ", ","),
            "channel": ("This call is from the ", " channel, "),
            "surveyor": ("on behalf of ", "."),
        },
    },
    "tam": {
        "voice_id": "RABOvaPec1ymXz02oDQi",
        "ctx": {
            "name": ("Hello ", ","),
            "channel": ("This call is from the ", " channel, "),
            "surveyor": ("on behalf of ", "."),
        },
    },
}
