# Generated by Django 5.0.1 on 2025-06-25 11:23

import api.models.error_verify_phone_dialer
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_phonedialer_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorVerifyPhoneDialer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_no', models.CharField(db_index=True, max_length=50)),
                ('trials', models.IntegerField(db_index=True)),
                ('status', models.CharField(choices=[('no_answer', 'No Answer'), ('no_dtmf', 'No DTMF'), ('rejected', 'Rejected'), ('accepted', 'Accepted')], db_index=True, max_length=20)),
                ('attempted_at', models.DateTimeField(db_index=True, default=api.models.error_verify_phone_dialer.now_ist_naive)),
                ('response_code', models.IntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'api_error_verify_phone_dialer',
                'indexes': [models.Index(fields=['ref_no'], name='api_error_v_ref_no_23bbe3_idx'), models.Index(fields=['trials'], name='api_error_v_trials_545a08_idx'), models.Index(fields=['status'], name='api_error_v_status_978f07_idx'), models.Index(fields=['attempted_at'], name='api_error_v_attempt_815dc5_idx')],
            },
        ),
    ]
