[basic-context]
exten => _XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX,1,Verbose(1,"User dialed ${EXTEN}")
 same => n,Set(PHONE=${EXTEN:0:10})
 same => n,Set(CHANNEL_RAW=${EXTEN:10:4})
 same => n,Set(CALLERID_NUM=${CHANNEL_RAW})
 same => n,Set(USER_ID=${EXTEN:14:8})
 same => n,Set(DIALPLAN=${EXTEN:22:10})
 same => n,System(/home/pi/Documents/32GSMgatewayServer/dtmf.sh start_dialing ${PHONE} ${CALLERID_NUM} ${USER_ID} ${DIALPLAN} &)
 ; We removed the not_answered line from here because it is never reached
 same => n,Dial(PJSIP/${PHONE}@${CALLERID_NUM},${INTERNAL_DIAL_OPT},U(${DIALPLAN}^${DIALPLAN}^${PHONE}^${CALLERID_NUM}^${USER_ID}^${DIALPLAN}))
 same => n,Hangup()

exten => h,1,NoOp(Final Dial Status: ${DIALSTATUS})
 ; If the call was answered, run the completed script
 same => n,ExecIf($["${DIALSTATUS}" = "ANSWER"]?System(/home/pi/Documents/32GSMgatewayServer/dtmf.sh completed ${PHONE} ${CALLERID_NUM} ${USER_ID} ${DIALPLAN} &))
 ; If the call was NOT answered (BUSY, NOANSWER, CONGESTION, etc.), run the not_answered script
 same => n,ExecIf($["${DIALSTATUS}" != "ANSWER"]?System(/home/pi/Documents/32GSMgatewayServer/dtmf.sh not_answered ${PHONE} ${CALLERID_NUM} ${USER_ID} ${DIALPLAN} ${DIALSTATUS} &))
 same => n,Hangup()

; Include the rest of the dialplan here:
#include /home/pi/Documents/32GSMgatewayServer/asterisk_dialplan.conf
