# Generated by Django 4.2.6 on 2024-02-08 10:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_dialplan_sms_id_campaign_language_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callstatus',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='dialplan',
            name='sms_id',
        ),
        migrations.AddField(
            model_name='campaign',
            name='language',
            field=models.CharField(choices=[('hi', 'Hindi'), ('en', 'English'), ('pa', 'Punjabi'), ('mr', 'Marathi'), ('gu', 'Gujarati'), ('bn', 'Bengali'), ('ta', 'Tamil'), ('te', 'Telugu'), ('ml', 'Malayalam'), ('ka', 'Kannada'), ('as', 'Assamese'), ('or', 'Oriya')], default='hi', max_length=2),
        ),
        migrations.AddField(
            model_name='campaign',
            name='voice_gender',
            field=models.IntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Others')], default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AddField(
            model_name='dialplan',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_id', to='api.smstemplate'),
        ),
    ]
