# Generated by Django 4.2.6 on 2024-02-08 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_sms_id_dialplan_template_dialplan_name_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='language',
            field=models.CharField(blank=True, default='Hindi', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='name_gender',
            field=models.IntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Others')], default=1),
        ),
    ]
