# Generated by Django 4.2.6 on 2024-02-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_siminformation_call_status_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siminformation',
            name='last_call_time',
            field=models.DateTimeField(blank=True, db_index=True, default='2024-02-17 11:34:14', null=True),
        ),
        migrations.AlterField(
            model_name='siminformation',
            name='last_validity_check',
            field=models.DateTimeField(blank=True, db_index=True, default='2024-02-17 11:34:14', null=True),
        ),
    ]
