# Generated by Django 4.2.6 on 2024-02-09 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_calldtmfstatus_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callstatus',
            name='campaign',
        ),
        migrations.DeleteModel(
            name='CallDtmfStatus',
        ),
        migrations.DeleteModel(
            name='CallStatus',
        ),
    ]
