# Generated by Django 4.2.6 on 2024-02-09 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_callstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallDtmfStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension', models.IntegerField(default=0)),
                ('dtmf_response', models.IntegerField(default=0)),
                ('call_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.callstatus')),
            ],
        ),
    ]
