# Generated by Django 4.2.6 on 2024-03-11 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_misscallmanagement_campaign_associated'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_id',
            field=models.CharField(default=10000001, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
