# Generated by Django 4.2.6 on 2024-02-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_smsdialer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smsdialer',
            old_name='status',
            new_name='sent_status',
        ),
        migrations.AddField(
            model_name='smsdialer',
            name='sent_datetime',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='smsdialer',
            name='sms_campaign_status',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
