# Generated by Django 4.2.6 on 2024-02-08 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_dialplan_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialplan',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_id', to='api.smstemplate'),
        ),
    ]
