# Generated by Django 4.2.6 on 2024-02-28 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_smsdialer_sms_through'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SmsRecord',
        ),
        migrations.AddField(
            model_name='smsdialer',
            name='sms_sent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='smstemplate',
            name='template_name',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
