# Generated by Django 4.2.11 on 2024-03-12 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_users_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='user_id',
        ),
    ]
