# Generated by Django 4.2.11 on 2024-03-13 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_phonedialer_duration'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='calldtmfstatus',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='calldtmfstatus',
            name='dial',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.phonedialer'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='calldtmfstatus',
            unique_together={('dial', 'extension')},
        ),
        migrations.RemoveField(
            model_name='calldtmfstatus',
            name='call_id',
        ),
    ]
