# Generated by Django 4.2.11 on 2024-03-13 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_calldtmfstatus_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calldtmfstatus',
            old_name='dial',
            new_name='call_id',
        ),
        migrations.AlterUniqueTogether(
            name='calldtmfstatus',
            unique_together={('call_id', 'extension')},
        ),
    ]
