# Generated by Django 4.2.6 on 2024-02-12 12:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_smscampaign_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='voice_gender',
        ),
        migrations.RemoveField(
            model_name='dialplan',
            name='name_after',
        ),
        migrations.AddField(
            model_name='dialplan',
            name='name_spell',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)]),
        ),
    ]
