# Generated by Django 4.2.11 on 2024-03-18 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_contacts_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userhosts',
            name='book_time',
        ),
    ]
