# Generated by Django 4.2.6 on 2024-02-23 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_phonedialer_unique_together_callstatus_dial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='phonedialer',
            unique_together={('phone_number', 'campaign')},
        ),
    ]
