# Generated by Django 4.2.6 on 2024-02-23 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_phonedialer_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='phonedialer',
            unique_together=set(),
        ),
    ]
