# Generated by Django 4.2.11 on 2024-03-22 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_phonedialer_created_at_phonedialer_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='siminformation',
            name='today_sim_status',
            field=models.IntegerField(blank=True, db_index=True, default=1, null=True),
        ),
    ]
