# Generated by Django 4.2.11 on 2024-03-22 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_siminformation_today_sim_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='siminformation',
            name='call_after',
            field=models.IntegerField(blank=True, db_index=True, default=20, null=True),
        ),
    ]
