# Generated by Django 4.2.11 on 2024-03-26 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_siminformation_call_after'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siminformation',
            old_name='today_sim_status',
            new_name='today_block_status',
        ),
    ]
