# Generated by Django 4.2.11 on 2024-04-01 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_smsdialer_sms_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonedialer',
            name='block_trials',
            field=models.IntegerField(blank=True, db_index=True, default=0, null=True),
        ),
    ]
