# Generated by Django 4.2.11 on 2024-04-02 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_callinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='callinfo',
            name='status',
            field=models.IntegerField(blank=True, db_index=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='callinfo',
            name='campaign_id',
            field=models.IntegerField(blank=True, db_index=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='callinfo',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='callinfo',
            name='host',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='callinfo',
            name='id',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='callinfo',
            name='phone_number',
            field=models.BigIntegerField(blank=True, db_index=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='callinfo',
            name='port',
            field=models.IntegerField(blank=True, db_index=True, default=0, null=True),
        ),
    ]
