# Generated by Django 4.2.11 on 2024-04-18 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_misscallmanagement_update_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siminformation',
            name='today_block_status',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
    ]
