# Generated by Django 4.2.6 on 2024-02-26 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_misscalls'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='misscallmanagement',
            table='api_misscall_management',
        ),
        migrations.AlterModelTable(
            name='misscalls',
            table='api_misscalls',
        ),
    ]
