# Generated by Django 4.2.6 on 2024-02-27 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_misscallmanagement_management_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='misscallmanagement',
            name='management_id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
