# Generated by Django 4.2.6 on 2024-02-27 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_rename_user_id_smsdialer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smscampaign',
            name='template_id',
        ),
        migrations.AddField(
            model_name='smscampaign',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.smstemplate'),
        ),
    ]
