# Generated by Django 4.2.6 on 2024-02-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siminformation',
            name='call_status_date',
            field=models.DateField(blank=True, db_index=True, default='2024-02-17', null=True),
        ),
        migrations.AlterField(
            model_name='siminformation',
            name='sms_backup_date',
            field=models.DateField(blank=True, db_index=True, default='2024-02-17', null=True),
        ),
    ]
