# Generated by Django 4.2.6 on 2024-03-02 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='voices',
            table='api_audios',
        ),
    ]
