# Generated by Django 4.2.6 on 2024-02-27 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smsdialer',
            name='name',
        ),
    ]
