# Generated by Django 4.2.6 on 2024-02-07 05:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='no_key_voice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='no_key_voice', to='api.voices'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='wrong_key_voice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wrong_key_voice', to='api.voices'),
        ),
        migrations.AlterField(
            model_name='siminformation',
            name='last_validity_check',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 7, 10, 32, 13, 932275), null=True),
        ),
        migrations.AlterField(
            model_name='siminformation',
            name='sms_backup_date',
            field=models.DateField(blank=True, default=datetime.date(2024, 2, 7), null=True),
        ),
    ]
