# Generated by Django 4.2.6 on 2024-02-07 06:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siminformation',
            name='last_validity_check',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 7, 11, 34, 14, 455808), null=True),
        ),
    ]
