# Generated by Django 4.2.6 on 2024-02-27 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_smsdialer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsdialer',
            name='host',
            field=models.CharField(db_index=True, default=1, max_length=100),
            preserve_default=False,
        ),
    ]
