# Generated by Django 4.2.6 on 2024-02-07 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_siminformation_last_validity_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siminformation',
            name='last_validity_check',
            field=models.DateTimeField(blank=True, default='2024, 2, 7, 11, 34, 14', null=True),
        ),
        migrations.AlterField(
            model_name='siminformation',
            name='sms_backup_date',
            field=models.DateField(blank=True, default='2024, 2, 7', null=True),
        ),
    ]
