# Generated by Django 4.2.6 on 2024-03-05 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_voices_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
