# Generated by Django 4.2.6 on 2024-02-07 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_siminformation_last_validity_check_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='namepronunciation',
            name='pronunciation_url',
        ),
    ]
