# Generated by Django 4.2.6 on 2024-02-14 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_smscampaign_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smscampaign',
            name='category1',
        ),
        migrations.RemoveField(
            model_name='smscampaign',
            name='category2',
        ),
        migrations.RemoveField(
            model_name='smscampaign',
            name='category3',
        ),
        migrations.RemoveField(
            model_name='smscampaign',
            name='category4',
        ),
        migrations.RemoveField(
            model_name='smscampaign',
            name='category5',
        ),
        migrations.AddField(
            model_name='smscampaign',
            name='contact_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
