# Generated by Django 4.2.6 on 2024-02-27 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_smsdialer_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhosts',
            name='allow_sms',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
