# Generated by Django 4.2.6 on 2024-02-21 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_siminformation_last_call_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='api_key',
            field=models.CharField(db_index=True, default=122, max_length=255),
            preserve_default=False,
        ),
    ]
