# Generated by Django 4.2.6 on 2024-02-08 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_calldtmfstatus_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='calldtmfstatus',
            unique_together=set(),
        ),
    ]
