# Generated by Django 4.2.6 on 2024-02-14 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_smscampaign_category1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsDialer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('template_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('sms_campaign_id', models.IntegerField()),
                ('priority', models.IntegerField()),
                ('status', models.IntegerField(blank=True, default=1, null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
    ]
