# Generated by Django 4.2.6 on 2024-02-08 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_dialplan_name_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialplan',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.smstemplate'),
        ),
    ]
