# Generated by Django 4.2.6 on 2024-02-07 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_namepronunciation_pronunciation_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dialplan',
            old_name='main_voice_id',
            new_name='main_voice',
        ),
        migrations.RenameField(
            model_name='dialplan',
            old_name='option_voice_id',
            new_name='option_voice',
        ),
    ]
