# Generated by Django 4.2.6 on 2024-02-28 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_userhosts_allow_sms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smsdialer',
            name='host',
        ),
    ]
