# Generated by Django 4.2.6 on 2024-02-21 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_users_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='api_key',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
