# Generated by Django 4.2.6 on 2024-02-21 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_users_api_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneDialer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=15)),
                ('campaign_id', models.IntegerField(db_index=True)),
                ('priority', models.IntegerField(db_index=True)),
                ('sent_status', models.IntegerField(blank=True, db_index=True, default=0, null=True)),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(db_index=True)),
                ('start_time', models.TimeField(db_index=True)),
                ('end_time', models.TimeField(db_index=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('name_spell', models.IntegerField(blank=True, db_index=True, null=True)),
                ('sent_datetime', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('campaign_status', models.IntegerField(blank=True, db_index=True, default=1, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_phone_dialer',
                'unique_together': {('phone_number', 'campaign_id')},
            },
        ),
    ]
