# Generated by Django 4.2.6 on 2024-02-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_calldtmfstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialplan',
            name='dtmf_0',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dialplan',
            name='dtmf_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dialplan',
            name='dtmf_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dialplan',
            name='dtmf_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dialplan',
            name='dtmf_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dialplan',
            name='dtmf_5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dialplan',
            name='dtmf_6',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dialplan',
            name='dtmf_7',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dialplan',
            name='dtmf_8',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dialplan',
            name='dtmf_9',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
