# Generated by Django 4.2.6 on 2024-02-21 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_phonedialer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonedialer',
            name='campaign_id',
        ),
        migrations.AddField(
            model_name='campaign',
            name='name_spell',
            field=models.IntegerField(blank=True, db_index=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='phonedialer',
            name='campaign',
            field=models.ForeignKey(default=1000000001, on_delete=django.db.models.deletion.CASCADE, to='api.campaign'),
            preserve_default=False,
        ),
    ]
