# Generated by Django 4.2.11 on 2024-03-12 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_users_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_id',
            field=models.CharField(db_index=True, default=98766, max_length=255),
            preserve_default=False,
        ),
    ]
