# Generated by Django 4.2.6 on 2024-02-08 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_dialplan_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='language',
            field=models.CharField(choices=[('hi', 'Hindi'), ('en', 'English'), ('pa', 'Punjabi'), ('mr', 'Marathi'), ('gu', 'Gujarati'), ('bn', 'Bengali'), ('ta', 'Tamil'), ('te', 'Telugu'), ('ml', 'Malayalam'), ('ka', 'Kannada'), ('as', 'Assamese'), ('or', 'Oriya')], default='hi', max_length=2),
        ),
    ]
