# Generated by Django 4.2.6 on 2024-02-12 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_dialplan_dtmf_0_alter_dialplan_dtmf_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('priority', models.IntegerField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('template_id', models.IntegerField()),
                ('category1', models.CharField(blank=True, max_length=255, null=True)),
                ('category2', models.CharField(blank=True, max_length=255, null=True)),
                ('category3', models.CharField(blank=True, max_length=255, null=True)),
                ('category4', models.CharField(blank=True, max_length=255, null=True)),
                ('category5', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'SmsCampaign',
            },
        ),
    ]
