# Generated by Django 4.2.6 on 2024-02-14 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_status_smsdialer_sent_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='pronunciation_status',
        ),
    ]
