# Generated by Django 4.2.6 on 2024-02-08 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_campaign_language'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='campaign',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='language',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='name_gender',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='no_key_voice',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='wrong_key_voice',
        ),
    ]
