# Generated by Django 4.2.6 on 2024-02-21 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_phonedialer_campaign_id_campaign_name_spell_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonedialer',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='phonedialer',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='phonedialer',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='phonedialer',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='phonedialer',
            name='start_time',
        ),
    ]
