# Generated by Django 4.2.6 on 2024-02-14 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_contacts_pronunciation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsdialer',
            name='sent_status',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
