# Generated by Django 4.2.6 on 2024-02-12 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_smscampaign_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='siminformation',
            name='call_time_today',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='siminformation',
            name='call_time_total',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='siminformation',
            name='calls_made_today',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='siminformation',
            name='calls_made_total',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
