# Generated by Django 4.2.6 on 2024-02-08 09:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_campaign_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='language',
            field=models.CharField(choices=[('hi', 'Hindi'), ('en', 'English'), ('pa', 'Punjabi'), ('mr', 'Marathi'), ('gu', 'Gujarati'), ('bn', 'Bengali'), ('ta', 'Tamil'), ('te', 'Telugu'), ('ml', 'Malayalam'), ('ka', 'Kannada'), ('as', 'Assamese'), ('or', 'Oriya')], default='hi', max_length=2),
        ),
        migrations.AddField(
            model_name='campaign',
            name='no_key_voice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='no_key_voice', to='api.voices'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='voice_gender',
            field=models.IntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Others')], default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AddField(
            model_name='campaign',
            name='wrong_key_voice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wrong_key_voice', to='api.voices'),
        ),
        migrations.AlterUniqueTogether(
            name='campaign',
            unique_together={('name', 'user')},
        ),
    ]
