# Generated by Django 4.2.6 on 2024-02-21 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_phonedialer_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonedialer',
            name='campaign_status',
        ),
        migrations.RemoveField(
            model_name='phonedialer',
            name='name_spell',
        ),
    ]
