# Generated by Django 4.2.6 on 2024-02-14 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_smsdialer_sent_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='smsdialer',
            unique_together={('phone_number', 'sms_campaign_id')},
        ),
        migrations.AlterModelTable(
            name='smsdialer',
            table='api_sms_dialer',
        ),
    ]
