# Generated by Django 4.2.6 on 2024-02-12 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_siminformation_call_time_today_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smscampaign',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='smscampaign',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
