# Generated by Django 4.2.6 on 2024-02-14 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_smsdialer_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsdialer',
            name='user_id',
            field=models.ForeignKey(default=100002, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
