# Generated by Django 4.2.6 on 2024-02-12 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_smscampaign_end_time_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='smscampaign',
            table=None,
        ),
    ]
