# Generated by Django 4.2.6 on 2024-02-15 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_smsdialer_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialplan',
            name='continue_to',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
