# Generated by Django 4.2.11 on 2024-03-16 07:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_dial_calldtmfstatus_call_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhosts',
            name='book_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
