# Generated by Django 4.2.6 on 2024-02-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_user_id_phonedialer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='allow_repeat',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='phonedialer',
            name='trials',
            field=models.IntegerField(blank=True, db_index=True, default=0, null=True),
        ),
    ]
