# Generated by Django 4.2.6 on 2024-02-15 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_dialplan_continue_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='contacts_count',
            field=models.IntegerField(default=0),
        ),
    ]
