# Generated by Django 4.2.6 on 2024-02-28 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_smstemplate_template_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smstemplate',
            name='template_name',
            field=models.CharField(db_index=True, max_length=750),
        ),
    ]
