# Generated by Django 4.2.6 on 2024-02-23 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_activecampaignhosts'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='phonedialer',
            unique_together=set(),
        ),
    ]
