# Generated by Django 4.2.6 on 2024-02-12 12:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_campaign_voice_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialplan',
            name='name_spell',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)]),
        ),
    ]
