# Generated by Django 4.2.6 on 2024-02-12 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_dialplan_name_spell'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dialplan',
            name='name_spell',
        ),
    ]
