# Generated by Django 4.2.11 on 2024-03-20 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_phonedialer_created_at_phonedialer_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonedialer',
            name='created_at',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='phonedialer',
            name='updated_at',
            field=models.DateTimeField(db_index=True),
        ),
    ]
