# Generated by Django 4.2.11 on 2024-03-20 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_phonedialer_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonedialer',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='phonedialer',
            name='updated_at',
        ),
    ]
