# Generated by Django 4.2.6 on 2024-02-28 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_smsdialer_sms_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smsdialer',
            name='sms_sent',
        ),
    ]
