# Generated by Django 4.2.11 on 2024-03-20 08:23

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_phonedialer_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonedialer',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phonedialer',
            name='updated_at',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 3, 20, 8, 23, 42, 536878, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
