# Generated by Django 4.2.6 on 2024-02-23 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_callstatus_dial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonedialer',
            name='call_through',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='phonedialer',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=10),
        ),
    ]
