# Generated by Django 4.2.6 on 2024-02-23 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_phonedialer_call_through_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callstatus',
            name='call_status',
        ),
    ]
