# Generated by Django 4.2.6 on 2024-02-23 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_callstatus_call_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smstemplate',
            name='template',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='voices',
            name='voice_desc',
            field=models.TextField(blank=True, null=True, verbose_name='voice_desc'),
        ),
    ]
