# Generated by Django 4.2.6 on 2024-02-23 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_smstemplate_template_alter_voices_voice_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callstatus',
            name='dial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.phonedialer'),
        ),
    ]
