# Generated by Django 4.2.11 on 2024-03-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_rename_today_sim_status_siminformation_today_block_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsdialer',
            name='sms_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
