# Generated by Django 4.2.6 on 2024-02-23 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_callstatus_dial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='calldtmfstatus',
            unique_together={('call_id', 'extension')},
        ),
    ]
