# Generated by Django 4.2.6 on 2024-02-23 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_calldtmfstatus_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callstatus',
            name='dial',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.phonedialer'),
        ),
    ]
