# Generated by Django 4.2.6 on 2024-02-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_callstatus_dial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userhosts',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='userhosts',
            name='priority',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='userhosts',
            name='status',
            field=models.IntegerField(db_index=True, default=1),
        ),
        migrations.AlterUniqueTogether(
            name='userhosts',
            unique_together={('host', 'priority')},
        ),
    ]
