# Generated by Django 4.2.11 on 2024-04-16 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_misscallmanagement_update_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='misscallmanagement',
            name='update_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
