# Generated by Django 4.2.6 on 2024-02-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_userhosts_unique_together_userhosts_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonedialer',
            name='name',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True),
        ),
    ]
