# Generated by Django 4.2.6 on 2024-02-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_phonedialer_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Misscalls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=10)),
                ('datetime', models.DateTimeField(db_index=True)),
                ('operator', models.CharField(db_index=True, max_length=50)),
                ('user_id', models.IntegerField(db_index=True)),
            ],
            options={
                'db_table': 'misscalls',
            },
        ),
    ]
