# Generated by Django 4.2.6 on 2024-02-26 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_misscalls'),
    ]

    operations = [
        migrations.CreateModel(
            name='MisscallManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('operator', models.CharField(db_index=True, max_length=50)),
                ('associated_number', models.CharField(db_index=True, max_length=15)),
                ('campaign_associated', models.CharField(db_index=True, max_length=50)),
                ('status', models.IntegerField(db_index=True)),
                ('send_sms_status', models.IntegerField(db_index=True)),
                ('sms_template', models.TextField(db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'misscall_management',
            },
        ),
        migrations.DeleteModel(
            name='Misscalls',
        ),
    ]
