# Generated by Django 4.2.6 on 2024-02-26 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_misscallmanagement_delete_misscalls'),
    ]

    operations = [
        migrations.CreateModel(
            name='Misscalls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=10)),
                ('datetime', models.DateTimeField(db_index=True)),
                ('misscall_management_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.misscallmanagement')),
            ],
            options={
                'db_table': 'misscalls',
            },
        ),
    ]
