# Generated by Django 4.2.6 on 2024-02-26 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_misscallmanagement_table_alter_misscalls_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='misscallmanagement',
            old_name='user',
            new_name='user_id',
        ),
    ]
