# Generated by Django 4.2.6 on 2024-02-26 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_smsrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='misscallmanagement',
            name='sms_template',
        ),
        migrations.AddField(
            model_name='misscallmanagement',
            name='sms_template_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.smstemplate'),
            preserve_default=False,
        ),
    ]
