# Generated by Django 4.2.6 on 2024-02-26 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_remove_misscallmanagement_sms_template_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='misscallmanagement',
            old_name='sms_template_id',
            new_name='sms_template',
        ),
    ]
