# Generated by Django 4.2.6 on 2024-02-27 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_rename_sms_template_id_misscallmanagement_sms_template'),
    ]

    operations = [
        migrations.RenameField(
            model_name='misscalls',
            old_name='misscall_management_id',
            new_name='misscall_management',
        ),
    ]
