# Generated by Django 4.2.6 on 2024-02-27 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_rename_user_id_misscallmanagement_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='misscallmanagement',
            name='campaign_associated',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
