# Generated by Django 4.2.6 on 2024-02-27 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_alter_misscallmanagement_campaign_associated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='misscallmanagement',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
