# Generated by Django 4.2.6 on 2024-02-27 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_alter_misscallmanagement_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='misscallmanagement',
            name='associated_number',
            field=models.CharField(blank=True, db_index=True, max_length=15, null=True),
        ),
    ]
