# Generated by Django 4.2.6 on 2024-02-27 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_alter_misscallmanagement_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='misscallmanagement',
            name='operator',
            field=models.CharField(db_index=True, max_length=11),
        ),
    ]
