# Generated by Django 4.2.6 on 2024-02-27 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_alter_misscallmanagement_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='misscalls',
            name='campaign',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.campaign'),
            preserve_default=False,
        ),
    ]
