# Generated by Django 4.2.6 on 2024-02-27 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_misscalls_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='misscalls',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.campaign'),
        ),
    ]
