# Generated by Django 4.2.6 on 2024-02-27 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_misscalls_number_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='misscalls',
            name='number_code',
        ),
    ]
