# Generated by Django 4.2.6 on 2024-02-27 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_remove_misscalls_number_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smsdialer',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='smsdialer',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='smsdialer',
            name='sms_campaign_status',
        ),
        migrations.RemoveField(
            model_name='smsdialer',
            name='start_time',
        ),
    ]
