# Generated by Django 4.2.6 on 2024-02-27 08:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_remove_smsdialer_end_time_remove_smsdialer_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smscampaign',
            name='end_date',
            field=models.DateField(db_index=True, default=datetime.date(2050, 12, 31)),
        ),
        migrations.AddField(
            model_name='smscampaign',
            name='start_date',
            field=models.DateField(db_index=True, default=datetime.date(2024, 1, 1)),
        ),
    ]
