# Generated by Django 4.2.6 on 2024-02-27 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_smscampaign_end_date_smscampaign_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smsdialer',
            name='sms_campaign_id',
        ),
        migrations.RemoveField(
            model_name='smsdialer',
            name='template_id',
        ),
        migrations.AddField(
            model_name='smsdialer',
            name='sms_campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.smscampaign'),
        ),
    ]
