# Generated by Django 4.2.6 on 2024-02-27 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_remove_smsdialer_sms_campaign_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smsdialer',
            old_name='user_id',
            new_name='user',
        ),
    ]
